# This is a basic workflow to help you get started with Actions

name: CI && CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is for the installation of the dependencies
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure Git
        run: |
          git config --global user.name "darshil89"
          git config --global user.email "darshilmahraur67@gmail.com"

      - name: Install Dependencies
        run: npm install

    if: (github.event_name == 'pull_request'  && github.event.action == 'opened' || github.event.action == 'synchronize') || github.event_name == 'push'

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mahraurdarshil89/github-actions:temporary .

      - name: Push temporary Docker image
        run: docker push mahraurdarshil89/github-actions:temporary

    # Run this job only when it's not a pull request or when a pull request is closed and merged
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull temporary Docker image
        run: docker pull mahraurdarshil89/github-actions:temporary

      - name: Retag Docker image
        run: docker tag mahraurdarshil89/github-actions:temporary mahraurdarshil89/github-actions:latest

      - name: Push Docker image
        run: docker push mahraurdarshil89/github-actions:latest

    # Run this job only when it's not a pull request or when a pull request is closed and merged
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: this is a test to check wheather both jobs runs parallely
        run: echo I am Darshil

    # Run this job only when it's not a pull request or when a pull request is closed and merged
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
